language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: latest
      dotnet: 2.0.2

before_script:
  - chmod +x ./build.sh
script:
  - dotnet --info
  - ./build.sh
